// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthorizedMember struct {
	ServerConfigID int64
	MemberID       string
}

type AuthorizedRole struct {
	ServerConfigID int64
	RoleID         string
}

type AutoCloseConfig struct {
	ServerConfigID                   int64
	IsActive                         bool
	CloseOnUserLeave                 bool
	CloseSinceOpenWithNoResponseMins pgtype.Int4
	CloseSinceLastMessageMins        pgtype.Int4
}

type MultiPanelConfig struct {
	ID             int32
	ServerConfigID int64
	Title          string
	Content        pgtype.Text
	EmbedColor     int32
	ChannelID      string
	LargeImgUrl    pgtype.Text
	SmallImgUrl    pgtype.Text
	UseDropdown    bool
	PanelConfigIds []int32
	Footer         pgtype.Text
	FootIconUrl    pgtype.Text
}

type PanelConfig struct {
	ID                 int32
	ServerConfigID     int64
	MentionRolesOnOpen []string
	CategoryID         pgtype.Text
	Title              string
	Content            pgtype.Text
	EmbedColor         int32
	ChannelID          string
	BtnColor           string
	BtnTxt             string
	BtnEmoji           pgtype.Text
	LargeImgUrl        pgtype.Text
	SmallImgUrl        pgtype.Text
}

type QuestionsConfig struct {
	ID            int32
	PanelConfigID int32
	Questions     []string
	RequiredFlags []bool
}

type ServerConfig struct {
	ID                  int64
	TicketNameStyle     string
	TicketTranscriptCid pgtype.Text
	MaxTicketPerUser    int32
	TicketPermissions   []byte
	MaxPanel            pgtype.Int4
	MaxMultiPanel       pgtype.Int4
}

type Transcript struct {
	ID               int32
	ServerConfigID   int64
	TicketID         pgtype.Text
	Username         pgtype.Text
	UserID           pgtype.Text
	OpenedAt         int64
	ClosedAt         int64
	ClosedBy         string
	StorageKey       string
	TotalMessages    pgtype.Int4
	TotalAttachments pgtype.Int4
	TotalEmbeds      pgtype.Int4
}

type WelcomeMsgConfig struct {
	ID            int32
	PanelConfigID int32
	EmbedColor    int32
	Title         string
	Description   string
	TitleUrl      pgtype.Text
	LargeImgUrl   pgtype.Text
	SmallImgUrl   pgtype.Text
	Footer        pgtype.Text
	FooterIconUrl pgtype.Text
}
